version: "3.8"

services:
  devops-app-1:
    build: .
    container_name: devops-app-1
    # No exponemos puertos al host, solo dentro de la red docker
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  devops-app-2:
    build: .
    container_name: devops-app-2
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  devops-nginx:
    image: nginx:1.27-alpine
    container_name: devops-nginx
    ports:
      - "8080:80"   # Exponemos el balanceador en el puerto 8080 del host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - devops-app-1
      - devops-app-2
